{{ if .Values.internalLB }}
## use this to aggregate internal pods behind
## a single load balanced IP
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ilb
  labels:
    chain: {{ .Values.iotex.chain_id }}
{{ include "iotex.labels" . | indent 4 }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    cloud.google.com/network-tier: "PREMIUM"
spec:
  type: LoadBalancer
  {{ if .Values.internalLBIP }}
  loadBalancerIP: {{ .Values.internalLBIP }}
  {{ end }}
  ports:
    - name: {{ .Values.service.rpcPortName }}
      port: {{ .Values.service.rpcPort }}
      targetPort: {{ .Values.service.rpcPortName }}
    - name: {{ .Values.service.p2pPortName }}
      port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPortName }}
  selector:
    app.kubernetes.io/name: {{ include "iotex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
