apiVersion: v1
kind: Secret
metadata:
  name:  "{{ .Release.Name }}-env"
  labels:
{{ include "iotex.labels" . | indent 4 }}
type: Opaque
data:
  HOME: {{ .Values.iotex.base_path | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  "{{ .Release.Name }}-config"
  labels:
{{ include "iotex.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.iotex.configurationFileName }}: |-
  {{- include (print $.Template.BasePath "/_config.yaml") . | b64enc | nindent 4 }}
